export const CONTACT_SEND_MESSAGE_START = 'CONTACT_SEND_MESSAGE_START';
export const CONTACT_SEND_MESSAGE_FINISH = 'CONTACT_SEND_MESSAGE_FINISH';
export const CLEAR_FROM_CONTACT_STATE = 'CLEAR_FROM_CONTACT_STATE';
